baseURL = 'https://yudi-azvd.github.io'
languageCode = 'pt-br'
title = 'Yudi Yamane'

theme = 'hugo-bearcub'

defaultContentLanguage = 'pt'
enableRobotsTXT = true
removePathAccents = true

ignoreLogs = ['warning-goldmark-raw-html']

description = 'Essa linda descrição'

# Quando habilitado, emite warnings pra vários paths, mesmo
# não tendo duplicatas, aparentemente. Pra comparação, quando é
# usado o site mais básico, warnings semelhantes são emitidos.
# pra reproduizr basta: (https://gohugo.io/getting-started/quick-start/#create-a-site)
#     hugo new site quickstart
#     cd quickstart
#     git init
#     git submodule add https://github.com/theNewDynamic/gohugo-theme-ananke.git themes/ananke
#     echo "theme = 'ananke'" >> hugo.toml
#     hugo server --printPathWarnings
# TODO: Ainda assim, eu queria deixar habilitado por segurança
# printPathWarnings = true


[permalinks]
  posts = "/:title"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = true
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false

    # https://xyproto.github.io/splash/docs/
    style = "monokai"
    # Gostei desses tabmém:
    # style = "emacs"
    # style = "perldoc"
    # style = "pastie" # Não fosse o highlight esquisito nas strings
    # style = "native"
    # style = "doom-one2"
    # style = "catppuccin-frappe"

# Multilingual mode config. More for information about how to setup translation,
# see https://gohugo.io/content-management/multilingual/
[languages]
  [languages.pt]
    title = "Yudi Yamane"
    languageName = "pt-BR 🇧🇷"
    LanguageCode = "pt-BR"
    contentDir = "content"
    [languages.pt.params]
      madeWith = "Oi"

[params]
  title = 'Yudi Yamane'
  description = 'Essa linda descrição'
  madeWith = 'Oi'

  favicon = 'images/logo.png'

[params.author]
  name = 'Yudi Yamane' # Your name as shown in the RSS feed metadata
  email = 'yudiyamane@gmail.com' # Added to the footer so readers can reply to posts

